emotions =  [   ["Normal"], 
                ["Feliz", "bien","feliz","alegre","contento","encantado","extasiado","eufórico","contento","alegre","alegría","jubiloso","animado" ,  "lleno de alegría", "pacífico", "agradable", "complacido", "emocionado", "optimista", "bendecido", "dichoso",  "no me puedo quejar", "cautivado", "contento", "agradable", "exultante", "volando alto",  "gratificado", "intoxicado", " riendo", "ligero", "bien visto", "en la nube nueve", "animado"],
                ["Triste", "decepcionado", "disgustado","peor", "amargo", "desconsolado", "melancolía", "triste", "pesimista", "sombrío",  "perdón", "melancólico", "desconsolado" ,"azul","triste","desanimado","desesperado","desanimado","desconsolado","triste","triste","abajo","abajo","abajo","boca abajo"," abatido","desamparado","sombrío","sombrío","doloroso","afligido","descorazonado","pesado","dolido","de capa caída","en pena","en los vertederos ","languideciendo","bajo","malhumorado","lúgubre","morboso","malhumorado","malhumorado","pensativo","enfermo","perturbado","lloroso" ,"desconsolado",
                "abatido", "abatido", "desanimado", "desanimado", "desconsolado", "desanimado", "caído", "abatido", "deprimido", "decepcionado", "descorazonado", "desanimado", "desmoralizado", "aplastado", "desolado", "desconsolado", "desconsolado", "con el corazón apesadumbrado", "decaído", "de capa caída", "triste", " infeliz", "triste", "melancólico", "miserable", "afligido", "desamparado", "cara alargada", "harto", "miserable", "sombrío", "sombrío", "lúgubre", "avergonzado", "ahorcado"],
                ["Enojado", "Furioso","nunca", "peor", "enojado", "molesto", "amargo", "enfurecido", "exasperado", "furioso", "acalorado", "apasionado", "indignado", "furioso" , "irritado", "irritado", "ofendido", "indignado", "resentido", "malhumorado", "tenso", "ofendido", "antagonizado", "irritado", "colérico", "convulsionado", " cruz", "disgustado", "exacerbado", "feroz", "feroz", "ardiente", "furioso", "irritado", "odioso", "caliente", "enfadado", "malhumorado", " indignado", "inflamado", "enfurecido", "irascible", "irascible", "enloquecido", "irritado", "picado", "provocado", "rabioso", "irritado", "dolorido", "esplenético" , "tormenta", "malhumorado", "turbulento", "turbulento"],
                ["Asustado", "miedo","deprimido", "desanimado", "malhumorado", "pesimista", "triste", "infeliz", "sangrado", "azul", "abatido", "destruido", "desanimado", "abajo" , "arrastrado", "dolido", "bajo", "arrancado", "llorando", "malo", "desanimado", "abatido", "caído", "malhumorado", "desconsolado", "abajo y fuera", "abajo en los vertederos", "abajo en la boca", "abatido", "desanimado", "harto", "sombrío", "sombrío", "en un funk azul", "en dolor" , "en los vertederos", "en los pozos", "en el baño", "decepcionado", "bajo-abajo", "bajo-espíritu", "lúgubre", "melancólico", "malhumorado", "en una decepción", "historia de sollozos", "sin espíritu", "derribado", "destrozado", "desgraciado"],
                ["Really"],
                ["Sorprendido", "Exitado", "emocionado"],   
                ["Amor","dulce", "hermoso", "caliente", "enfermo de amor", "coqueto", "cariño", "admiro", "adorable", "cariño", "amor", "ángel", "increíble" , "atracción", "bebé", "bebé", "miel", "linda", "linda", "linda", "cuidado", "encantador", "cupido", "elegante", "novia", " novio", "San Valentín", "hermoso", "magdalena", "travieso", "pasión", "reina", "descarado", "seductor", "cariño", "unqiue", "cálido"] ,
                ["Disparar","disparo","dispara""arma","bala","pistola"] ,       
            ]




